# Generated by Django 2.0.2 on 2018-03-05 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180305_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='blocked_friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='friends',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='friends',
            name='follows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None),
        ),
    ]
